<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31883" started-at="2019-01-31T11:34:28Z" finished-at="2019-01-31T11:34:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31883" started-at="2019-01-31T11:34:28Z" finished-at="2019-01-31T11:34:59Z">
      <class name="TestCase.FBlogin">
        <test-method status="PASS" signature="startReport()[pri:0, instance:TestCase.FBlogin@5622fdf]" name="startReport" is-config="true" duration-ms="303" started-at="2019-01-31T16:34:28Z" finished-at="2019-01-31T16:34:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="FacebookLogin()[pri:0, instance:TestCase.FBlogin@5622fdf]" name="FacebookLogin" duration-ms="17517" started-at="2019-01-31T16:34:28Z" finished-at="2019-01-31T16:34:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FacebookLogin -->
        <test-method status="PASS" signature="GetResults(org.testng.ITestResult)[pri:0, instance:TestCase.FBlogin@5622fdf]" name="GetResults" is-config="true" duration-ms="4" started-at="2019-01-31T16:34:45Z" finished-at="2019-01-31T16:34:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=FacebookLogin status=SUCCESS method=FBlogin.FacebookLogin()[pri:0, instance:TestCase.FBlogin@5622fdf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetResults -->
        <test-method status="FAIL" signature="FacebookLogin2()[pri:0, instance:TestCase.FBlogin@5622fdf]" name="FacebookLogin2" duration-ms="12534" started-at="2019-01-31T16:34:45Z" finished-at="2019-01-31T16:34:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestCase.FBlogin.FacebookLogin2(FBlogin.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FacebookLogin2 -->
        <test-method status="PASS" signature="GetResults(org.testng.ITestResult)[pri:0, instance:TestCase.FBlogin@5622fdf]" name="GetResults" is-config="true" duration-ms="350" started-at="2019-01-31T16:34:58Z" finished-at="2019-01-31T16:34:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=FacebookLogin2 status=FAILURE method=FBlogin.FacebookLogin2()[pri:0, instance:TestCase.FBlogin@5622fdf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetResults -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCase.FBlogin@5622fdf]" name="tearDown" is-config="true" duration-ms="1136" started-at="2019-01-31T16:34:58Z" finished-at="2019-01-31T16:34:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCase.FBlogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
